//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Happy_Tooth_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class doctor_schedule
    {
        public int schedule_id { get; set; }
        public int doctor_id { get; set; }
        public string day_of_week { get; set; }
        public System.TimeSpan start_time { get; set; }
        public System.TimeSpan end_time { get; set; }
    
        public virtual doctors doctors { get; set; }
    }
}
