//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyToothDLL_Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class visits
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public visits()
        {
            this.visit_services = new HashSet<visit_services>();
        }
    
        public int visit_id { get; set; }
        public int appointment_id { get; set; }
        public string diagnosis { get; set; }
        public string treatment { get; set; }
        public Nullable<decimal> total_price { get; set; }
    
        public virtual appointments appointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<visit_services> visit_services { get; set; }
    }
}
