//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyToothWebApplication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HappyToothEntities : DbContext
    {
        public HappyToothEntities()
            : base("name=HappyToothEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<appointments> appointments { get; set; }
        public virtual DbSet<doctor_schedule> doctor_schedule { get; set; }
        public virtual DbSet<doctors> doctors { get; set; }
        public virtual DbSet<patients> patients { get; set; }
        public virtual DbSet<services> services { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<visit_services> visit_services { get; set; }
        public virtual DbSet<visits> visits { get; set; }
    }
}
