//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyToothWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class visit_services
    {
        public int visit_id { get; set; }
        public int service_id { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual services services { get; set; }
        public virtual visits visits { get; set; }
    }
}
